/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNightRouteImport } from './routes/app.night'
import { Route as AppMoodRouteImport } from './routes/app.mood'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppCheckinsRouteImport } from './routes/app.checkins'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNightRoute = AppNightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodRoute = AppMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsRoute = AppCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/night': typeof AppNightRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/night': typeof AppNightRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/checkins': typeof AppCheckinsRoute
  '/app/focus': typeof AppFocusRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/mood': typeof AppMoodRoute
  '/app/night': typeof AppNightRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/checkins'
    | '/app/focus'
    | '/app/goals'
    | '/app/mood'
    | '/app/night'
    | '/app/profile'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/checkins'
    | '/app/focus'
    | '/app/goals'
    | '/app/mood'
    | '/app/night'
    | '/app/profile'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/checkins'
    | '/app/focus'
    | '/app/goals'
    | '/app/mood'
    | '/app/night'
    | '/app/profile'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/night': {
      id: '/app/night'
      path: '/night'
      fullPath: '/app/night'
      preLoaderRoute: typeof AppNightRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mood': {
      id: '/app/mood'
      path: '/mood'
      fullPath: '/app/mood'
      preLoaderRoute: typeof AppMoodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkins': {
      id: '/app/checkins'
      path: '/checkins'
      fullPath: '/app/checkins'
      preLoaderRoute: typeof AppCheckinsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckinsRoute: typeof AppCheckinsRoute
  AppFocusRoute: typeof AppFocusRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMoodRoute: typeof AppMoodRoute
  AppNightRoute: typeof AppNightRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinsRoute: AppCheckinsRoute,
  AppFocusRoute: AppFocusRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMoodRoute: AppMoodRoute,
  AppNightRoute: AppNightRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
